# Generated by Django 2.1.2 on 2018-11-01 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemDesc',
            fields=[
                ('item_desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('zip_code', models.IntegerField()),
                ('city_name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('is_seller', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Wallet'),
        ),
        migrations.AddField(
            model_name='order',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='store.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ItemDesc'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Inventory'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='b_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='o_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Order'),
        ),
    ]
