# Generated by Django 2.1.3 on 2018-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20181102_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
