# Generated by Django 2.1.2 on 2018-11-01 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20181025_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Location')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status', models.IntegerField()),
                ('item_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDesc',
            fields=[
                ('item_desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Buyer')),
                ('items', models.ManyToManyField(to='store.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='loc',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='seller',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Wallet'),
        ),
        migrations.AddField(
            model_name='order',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Seller'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ItemDesc'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Inventory'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Seller'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='s_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Seller'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Wallet'),
        ),
    ]
