# Generated by Django 2.1.2 on 2018-11-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181101_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_buyer',
        ),
    ]
